module.exports = {
  "select": true,
  "selectAll": true,
  "removeElements": true,
  "createDiv": true,
  "createP": true,
  "createSpan": true,
  "createImg": true,
  "createA": true,
  "createSlider": true,
  "createButton": true,
  "createCheckbox": true,
  "createSelect": true,
  "createRadio": true,
  "createFileInput": true,
  "createVideo": true,
  "createAudio": true,
  "VIDEO": true,
  "AUDIO": true,
  "createCapture": true,
  "createElement": true
};
